feat: wire up some components
muxable/stream-dashboard pull request #54
Opened 2021-10-29 01:14 UTC by chungwwei

2021-11-05 20:27 UTC, juaoose requested changes

2021-11-05 20:27 UTC, juaoose commented on src/component/ComposedTwoYAxisChart.tsx
> +  const formatted = data.map((d, index) => {
`index` is not used

2021-11-05 20:27 UTC, juaoose commented on src/component/Map.tsx
> +              x: {x} <br />
I guess it could be nicer as latitude and longitude, if you agree.

2021-11-05 20:27 UTC, juaoose commented on src/screens/Analytics.tsx
> +    async function loadStreamData(streamId: string) {
Would it be better to break this function into smaller ones so that its easier to follow?

2021-11-06 00:16 UTC, Leeoku commented
did a general review and wrote what stood out right away. I'll do more indepth to learn/ask questions later

2021-11-07 16:27 UTC, Leeoku approved these changes

2021-11-07 16:27 UTC, Leeoku commented on src/screens/Analytics.tsx
> +            {value === 0 && <ComposedTwoYAxisChart data={streamData} />}
a suggestion. Should we write a comment or change the value to match the tab name, make it readable for others?

2021-11-12 02:54 UTC, juaoose approved these changes

2021-11-12 02:55 UTC, merged