feat: initial heat map
muxable/stream-dashboard pull request #73
Opened 2021-11-30 02:06 UTC by chungwwei

it's the example code from mapbox with a little modification from me. Since it's using mapbox, you need to create a mapbox account and create a token, and create a `.env.local` file in `src` and put the mapbox token there to see map.

I don't really know how to style the heatmap in `MapStyle.ts`, doesn't look easy to me.

2021-11-30 10:27 UTC, kevmo314 commented
> I don't really know how to style the heatmap in `MapStyle.ts`, doesn't look easy to me.

What did you try? This would make a great mini Thursday talk :)

2021-12-02 14:10 UTC, juaoose commented
Would the Mapbox access token be in the build config? Like in the stream-dashboard project secrets?

2021-12-02 14:12 UTC, kevmo314 commented
Nah the mapbox token can be shared publicly so it can be in the source

On Thu, Dec 2, 2021, 9:10 AM Juan ***@***.***> wrote:

> Would the Mapbox access token be in the build config? Like in the
> stream-dashboard project secrets?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/muxable/stream-dashboard/pull/73#issuecomment-984662196>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAD423XTIBSBHZJTUB64J2TUO5465ANCNFSM5JASZLGA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-03 01:00 UTC, juaoose requested changes

2021-12-03 01:00 UTC, juaoose commented on src/component/GlobalHeatMap.tsx
> +const MAPBOX_TOKEN = ""; // Set your mapbox token here
```suggestion
const MAPBOX_TOKEN = "pk.eyJ1Ijoia2V2bW8zMTQiLCJhIjoiY2t3bjR3cTloMDJ1ajJ1cW9obGh2ZmcybCJ9.uWdEuy9ilDupIiaOQIcMpQ"; 
```

2021-12-06 23:43 UTC, juaoose approved these changes

2021-12-07 03:04 UTC, merged